import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  foreignKey,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { users } from "./auth";
import { organizations } from "./organizations";

export const tickets = pgTable(
  "tickets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Generated by Postgres function `generate_ticket_number()` (added in migration).
    ticketNumber: text("ticket_number").notNull().unique(),
    subject: text("subject").notNull(),
    description: text("description").notNull(),
    category: text("category").notNull(),
    // Work type (admin-managed via `ticket_types`): service_request | incident |
    // change | project | alert (extensible). Defaults to the standard
    // "service_request" so existing rows and untriaged tickets have a value.
    // Validated in the app layer against the active types (like category).
    type: text("type").notNull().default("service_request"),
    priority: text("priority").notNull(),
    status: text("status").notNull().default("open"),
    stream: text("stream").notNull(),
    origin: text("origin").notNull(),
    // Finer-grained creation source than `origin` (which is only
    // web_form/email/portal). Distinguishes a direct inbound email from a
    // staff-forwarded one, and a staff-created ("manual") ticket from a
    // customer portal submission. Nullable — pre-dates this column reads as
    // null and the UI falls back to `origin`.
    //   'direct_email' | 'forwarded_email' | 'manual' | 'portal' | 'web_form'
    createdVia: text("created_via"),
    // Organization that raised the ticket (Meeting-2, CR-02). Nullable so
    // guest/legacy submissions that don't match a registered org still work;
    // the org abbreviation drives the ticket-number prefix when present.
    organizationId: uuid("organization_id").references(() => organizations.id, {
      onDelete: "set null",
    }),
    customerId: uuid("customer_id").references(() => users.id, {
      onDelete: "set null",
    }),
    customerEmail: text("customer_email").notNull(),
    customerName: text("customer_name").notNull(),
    // Raw organization name the submitter typed (guest path). Kept verbatim
    // even when it doesn't match a registered org so a coordinator can
    // reconcile it later from the triage queue — previously this was discarded.
    customerCompany: text("customer_company"),
    // How the ticket's organization was determined:
    //   account    – from an authenticated customer's account org (trusted)
    //   domain     – matched by the submitter's email domain
    //   staff      – manually linked/confirmed by a coordinator
    //   unverified – a company was claimed but not confirmed (organizationId NULL)
    //   none       – no organization information at all
    // Only account/domain/staff set organizationId, so only those deduct from
    // a Monthly-Plan balance. 'unverified' rows are the triage queue.
    orgMatchStatus: text("org_match_status").notNull().default("none"),
    // Billing categorization (Meeting-2, CR-16). NULL until triaged; one of
    // yes | no | monthly_plan | project | rework. When 'monthly_plan', logged
    // work-log minutes are deducted from the org's monthly balance.
    billable: text("billable"),
    // Invoice number keyed in once the ticket has been billed. NULL/empty =
    // not yet invoiced. Drives the "Billed / Needs invoice" status shown on the
    // ticket, the tickets queue, and the work log.
    invoiceNumber: text("invoice_number"),
    // How many work-log minutes this ticket has already deducted from its
    // organization's Monthly-Plan balance (Meeting-2, CR-19). Lets the
    // deduction stay idempotent + reversible as logs change or billable
    // toggles — we only ever apply the delta against this number.
    monthlyPlanDeductedMinutes: integer("monthly_plan_deducted_minutes")
      .notNull()
      .default(0),
    assignedToId: uuid("assigned_to_id").references(() => users.id, {
      onDelete: "restrict",
    }),
    assignedAt: timestamp("assigned_at", { withTimezone: true }),
    isEscalated: boolean("is_escalated").notNull().default(false),
    escalatedAt: timestamp("escalated_at", { withTimezone: true }),
    escalatedById: uuid("escalated_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    // One of: beyond_scope | requires_access | critical_impact |
    // vendor_involvement | other  (NULL when not escalated). Enforced by
    // the `tickets_escalation_reason_check` CHECK constraint below so a
    // missed app-level validation can't poison the categorical column.
    escalationReason: text("escalation_reason"),
    // Free-text supplementary detail captured when the technician
    // escalates (optional). Lives next to the categorical reason so
    // reporting can group by enum without losing context.
    escalationNote: text("escalation_note"),
    // Who the ticket was escalated TO (Meeting-2, CR-14): the name of an
    // upper-hierarchy role (e.g. "IT Director", "Super Admin"). Free text so
    // it tracks whatever roles exist; NULL when not escalated.
    escalationTargetRole: text("escalation_target_role"),
    csatResponse: text("csat_response"),
    // Three-point emoji rating (CSAT feedback): happy | neutral | unhappy.
    // happy/neutral close the ticket; unhappy reopens it. `csatResponse` is
    // kept in lock-step as the binary state driver (happy/neutral -> satisfied,
    // unhappy -> unsatisfied) so the atomic close/reopen guards and existing
    // CSAT reports work unchanged; full per-review history + comments live in
    // the `ticket_reviews` table.
    csatRating: text("csat_rating"),
    csatRespondedAt: timestamp("csat_responded_at", { withTimezone: true }),
    responseDueAt: timestamp("response_due_at", { withTimezone: true }),
    resolutionDueAt: timestamp("resolution_due_at", { withTimezone: true }),
    firstResponseAt: timestamp("first_response_at", { withTimezone: true }),
    slaWarning50At: timestamp("sla_warning_50_at", { withTimezone: true }),
    slaWarning80At: timestamp("sla_warning_80_at", { withTimezone: true }),
    slaBreachedAt: timestamp("sla_breached_at", { withTimezone: true }),
    // When the SLA clock is currently PAUSED (ticket is awaiting the customer
    // or on hold), else NULL. On leaving a pause status the response/resolution
    // due dates are shifted forward by the paused span, so waiting time isn't
    // counted against the technician. Paused tickets are excluded from the SLA
    // monitor + boards so no warning/breach fires while the clock is stopped.
    slaPausedAt: timestamp("sla_paused_at", { withTimezone: true }),
    // Last time the SLA monitor re-nagged admins about this ticket AFTER its
    // initial breach. NULL = not re-nagged yet. Drives the configurable
    // repeat-escalation cadence (settings: sla.breach_repeat_hours).
    slaBreachRemindedAt: timestamp("sla_breach_reminded_at", {
      withTimezone: true,
    }),
    // Last time the unassigned-ticket monitor alerted admins about this
    // ticket having no owner. NULL = never alerted. Used for idempotency and
    // the configurable re-nag cadence (settings: unassigned_alert.*).
    unassignedReminderAt: timestamp("unassigned_reminder_at", {
      withTimezone: true,
    }),
    // When the "no customer response" follow-up nudge was last sent (the
    // customer-followup monitor). NULL = not yet nudged for the current agent
    // message; the value is compared against the latest agent message so a
    // fresh reply re-opens the nudge window without a separate reset.
    customerFollowupSentAt: timestamp("customer_followup_sent_at", {
      withTimezone: true,
    }),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    reopenedCount: integer("reopened_count").notNull().default(0),
    duplicateOfId: uuid("duplicate_of_id"),
    isAnonymized: boolean("is_anonymized").notNull().default(false),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    deletedById: uuid("deleted_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    index("tickets_status_priority_idx").on(t.status, t.priority),
    index("tickets_assigned_to_id_idx").on(t.assignedToId),
    index("tickets_organization_id_idx").on(t.organizationId),
    index("tickets_customer_id_idx").on(t.customerId),
    index("tickets_customer_email_idx").on(t.customerEmail),
    index("tickets_is_escalated_idx")
      .on(t.isEscalated)
      .where(sql`${t.isEscalated} = true`),
    index("tickets_created_at_idx").on(t.createdAt.desc()),
    index("tickets_resolution_due_at_idx")
      .on(t.resolutionDueAt)
      .where(sql`${t.status} NOT IN ('resolved', 'closed')`),
    index("tickets_closed_at_anonymize_idx")
      .on(t.closedAt)
      .where(sql`${t.isAnonymized} = false`),
    foreignKey({
      columns: [t.duplicateOfId],
      foreignColumns: [t.id],
      name: "tickets_duplicate_of_id_fk",
    }).onDelete("set null"),
    // NOTE: `category` used to be CHECK-constrained to a fixed set. It's now
    // an admin-managed list in `ticket_categories`, so the closed-set guard
    // moved to the application layer (create/edit actions validate against the
    // active categories). See src/lib/db/schema/ticket-categories.ts.
    check(
      "tickets_priority_check",
      sql`${t.priority} IN ('low','medium','high','critical')`,
    ),
    check(
      "tickets_status_check",
      sql`${t.status} IN ('draft','open','in_progress','awaiting_customer_confirmation','on_hold','escalation','resolved','closed')`,
    ),
    check(
      "tickets_billable_check",
      sql`${t.billable} IS NULL OR ${t.billable} IN ('yes','no','monthly_plan','project','rework')`,
    ),
    check(
      "tickets_org_match_status_check",
      sql`${t.orgMatchStatus} IN ('account','domain','staff','unverified','none')`,
    ),
    check("tickets_stream_check", sql`${t.stream} IN ('internal','external')`),
    check(
      "tickets_origin_check",
      sql`${t.origin} IN ('web_form','email','portal')`,
    ),
    check(
      "tickets_csat_check",
      sql`${t.csatResponse} IS NULL OR ${t.csatResponse} IN ('satisfied','unsatisfied')`,
    ),
    check(
      "tickets_csat_rating_check",
      sql`${t.csatRating} IS NULL OR ${t.csatRating} IN ('happy','neutral','unhappy')`,
    ),
    check(
      "tickets_escalation_reason_check",
      sql`${t.escalationReason} IS NULL OR ${t.escalationReason} IN ('beyond_scope','requires_access','critical_impact','vendor_involvement','other')`,
    ),
  ],
);
