import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  foreignKey,
  index,
  integer,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { users } from "./auth";

export const tickets = pgTable(
  "tickets",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Generated by Postgres function `generate_ticket_number()` (added in migration).
    ticketNumber: text("ticket_number").notNull().unique(),
    subject: text("subject").notNull(),
    description: text("description").notNull(),
    category: text("category").notNull(),
    priority: text("priority").notNull(),
    status: text("status").notNull().default("open"),
    stream: text("stream").notNull(),
    origin: text("origin").notNull(),
    customerId: uuid("customer_id").references(() => users.id, {
      onDelete: "set null",
    }),
    customerEmail: text("customer_email").notNull(),
    customerName: text("customer_name").notNull(),
    assignedToId: uuid("assigned_to_id").references(() => users.id, {
      onDelete: "restrict",
    }),
    assignedAt: timestamp("assigned_at", { withTimezone: true }),
    isEscalated: boolean("is_escalated").notNull().default(false),
    escalatedAt: timestamp("escalated_at", { withTimezone: true }),
    escalatedById: uuid("escalated_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    escalationReason: text("escalation_reason"),
    csatResponse: text("csat_response"),
    csatRespondedAt: timestamp("csat_responded_at", { withTimezone: true }),
    responseDueAt: timestamp("response_due_at", { withTimezone: true }),
    resolutionDueAt: timestamp("resolution_due_at", { withTimezone: true }),
    firstResponseAt: timestamp("first_response_at", { withTimezone: true }),
    slaWarning50At: timestamp("sla_warning_50_at", { withTimezone: true }),
    slaWarning80At: timestamp("sla_warning_80_at", { withTimezone: true }),
    slaBreachedAt: timestamp("sla_breached_at", { withTimezone: true }),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
    closedAt: timestamp("closed_at", { withTimezone: true }),
    reopenedCount: integer("reopened_count").notNull().default(0),
    duplicateOfId: uuid("duplicate_of_id"),
    isAnonymized: boolean("is_anonymized").notNull().default(false),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    deletedById: uuid("deleted_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .default(sql`now()`),
  },
  (t) => [
    index("tickets_status_priority_idx").on(t.status, t.priority),
    index("tickets_assigned_to_id_idx").on(t.assignedToId),
    index("tickets_customer_id_idx").on(t.customerId),
    index("tickets_customer_email_idx").on(t.customerEmail),
    index("tickets_is_escalated_idx")
      .on(t.isEscalated)
      .where(sql`${t.isEscalated} = true`),
    index("tickets_created_at_idx").on(t.createdAt.desc()),
    index("tickets_resolution_due_at_idx")
      .on(t.resolutionDueAt)
      .where(sql`${t.status} NOT IN ('resolved', 'closed')`),
    index("tickets_closed_at_anonymize_idx")
      .on(t.closedAt)
      .where(sql`${t.isAnonymized} = false`),
    foreignKey({
      columns: [t.duplicateOfId],
      foreignColumns: [t.id],
      name: "tickets_duplicate_of_id_fk",
    }).onDelete("set null"),
    check(
      "tickets_category_check",
      sql`${t.category} IN ('hardware','software','network','access','other')`,
    ),
    check(
      "tickets_priority_check",
      sql`${t.priority} IN ('low','medium','high','critical')`,
    ),
    check(
      "tickets_status_check",
      sql`${t.status} IN ('open','in_progress','resolved','closed')`,
    ),
    check("tickets_stream_check", sql`${t.stream} IN ('internal','external')`),
    check(
      "tickets_origin_check",
      sql`${t.origin} IN ('web_form','email','portal')`,
    ),
    check(
      "tickets_csat_check",
      sql`${t.csatResponse} IS NULL OR ${t.csatResponse} IN ('satisfied','unsatisfied')`,
    ),
  ],
);
