import { eq } from "drizzle-orm";
import { can } from "@/lib/auth/can";
import { productionContext } from "@/lib/auth/can-context";
import { getSessionUser } from "@/lib/auth/session";
import { db } from "@/lib/db/client";
import { users } from "@/lib/db/schema/auth";
import { type ExportDataset, parseExportFormat } from "@/lib/export/dataset";
import { exportResponse } from "@/lib/export/respond";
import {
  loadProcurementSpend,
  loadTicketHealth,
  parseReportRange,
  type ProcurementSpend,
  type ReportRange,
  type TicketHealth,
} from "@/lib/reports/queries";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const usd = new Intl.NumberFormat("en-US", {
  style: "currency",
  currency: "USD",
});
function pct(rate: number | null): string {
  return rate === null ? "—" : `${(rate * 100).toFixed(1)}%`;
}

function dayStr(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function buildDataset(
  tickets: TicketHealth,
  procurement: ProcurementSpend,
  generatedBy: string,
  range?: ReportRange,
): ExportDataset {
  const now = new Date();
  const scope = range
    ? `All organizations · ${dayStr(range.from)} to ${dayStr(range.to)}`
    : "All organizations, all time";

  // With a period selected the rolling-window figures don't apply — show a
  // single "in period" total instead of the 7-day / 30-day / all-time split.
  const ticketTotals = range
    ? [{ label: "Created (in period)", value: String(tickets.totalsByWindow.allTime) }]
    : [
        { label: "Created (last 7 days)", value: String(tickets.totalsByWindow.week) },
        { label: "Created (last 30 days)", value: String(tickets.totalsByWindow.month) },
        { label: "Total (all time)", value: String(tickets.totalsByWindow.allTime) },
      ];

  return {
    title: "IT Operations Report",
    subtitle: range
      ? `Ticket health & procurement spend · ${dayStr(range.from)} – ${dayStr(range.to)}`
      : "Ticket health & procurement spend",
    meta: [
      { label: "Generated by", value: generatedBy },
      {
        label: "Generated at",
        value: `${now.toISOString().slice(0, 16).replace("T", " ")} UTC`,
      },
      { label: "Scope", value: scope },
    ],
    sections: [
      {
        kind: "keyValues",
        title: "Ticket health",
        items: [
          ...ticketTotals,
          {
            label: "Average resolution",
            value:
              tickets.averageResolutionMinutes !== null
                ? `${tickets.averageResolutionMinutes} min`
                : "—",
          },
          { label: "CSAT rate", value: pct(tickets.csatRate.rate) },
          {
            label: "CSAT responses",
            value: `${tickets.csatRate.satisfied} satisfied · ${tickets.csatRate.unsatisfied} unsatisfied`,
          },
          { label: "Escalation rate", value: pct(tickets.escalationRate) },
          { label: "SLA compliance", value: pct(tickets.slaComplianceRate) },
        ],
      },
      {
        kind: "table",
        title: "Tickets by status",
        columns: ["Status", "Count"],
        align: ["left", "right"],
        rows: tickets.byStatus.map((r) => [r.status, r.count]),
      },
      {
        kind: "table",
        title: "Tickets by stream",
        columns: ["Stream", "Count"],
        align: ["left", "right"],
        rows: tickets.byStream.map((r) => [r.stream, r.count]),
      },
      {
        kind: "table",
        title: "Technician load",
        columns: ["Technician", "Assigned", "Resolved"],
        align: ["left", "right", "right"],
        rows: tickets.techLoad.map((r) => [r.name, r.assigned, r.resolved]),
      },
      {
        kind: "keyValues",
        title: "Procurement spend",
        items: [
          ...(range
            ? [
                {
                  label: "Spend (in period)",
                  value: usd.format(procurement.totalsByWindow.year),
                },
              ]
            : [
                { label: "Last 30 days", value: usd.format(procurement.totalsByWindow.month) },
                { label: "Last 90 days", value: usd.format(procurement.totalsByWindow.quarter) },
                { label: "Last 12 months", value: usd.format(procurement.totalsByWindow.year) },
              ]),
          {
            label: "Pending",
            value: `${procurement.pendingApprovals.count} request(s) · ${usd.format(procurement.pendingApprovals.total)}`,
          },
        ],
      },
      {
        kind: "table",
        title: "Procurement by type",
        columns: ["Type", "Total"],
        align: ["left", "right"],
        rows: procurement.byType.map((r) => [r.type, usd.format(r.total)]),
      },
      {
        kind: "table",
        title: "Procurement by stage",
        columns: ["Stage", "Count", "Total"],
        align: ["left", "right", "right"],
        rows: procurement.byStatus.map((r) => [r.status, r.count, usd.format(r.total)]),
      },
      {
        kind: "table",
        title: "Top procurement items",
        columns: ["Item", "Total"],
        align: ["left", "right"],
        rows: procurement.topItems.map((r) => [r.itemName, usd.format(r.total)]),
      },
    ],
  };
}

export async function GET(request: Request): Promise<Response> {
  const user = await getSessionUser();
  if (!user) return new Response("Unauthenticated", { status: 401 });
  if (
    !(await can(user, "reports.export", { type: "global" }, productionContext))
  ) {
    return new Response("Forbidden", { status: 403 });
  }

  const sp = new URL(request.url).searchParams;
  const format = parseExportFormat(sp.get("format"));
  const range = parseReportRange(
    sp.get("from") ?? undefined,
    sp.get("to") ?? undefined,
  );

  const [tickets, procurement, me] = await Promise.all([
    loadTicketHealth(range),
    loadProcurementSpend(range),
    db
      .select({ name: users.name })
      .from(users)
      .where(eq(users.id, user.id))
      .limit(1),
  ]);

  const dataset = buildDataset(tickets, procurement, me[0]?.name ?? "—", range);
  return exportResponse(dataset, format, "reports");
}
